// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseShift(arg1, arg2) {
  return window['go']['main']['App']['CloseShift'](arg1, arg2);
}

export function CreateOrder(arg1, arg2) {
  return window['go']['main']['App']['CreateOrder'](arg1, arg2);
}

export function CreateUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3);
}

export function Dashboard(arg1) {
  return window['go']['main']['App']['Dashboard'](arg1);
}

export function DeleteUser(arg1, arg2) {
  return window['go']['main']['App']['DeleteUser'](arg1, arg2);
}

export function DriverRating(arg1) {
  return window['go']['main']['App']['DriverRating'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function ListAudit(arg1) {
  return window['go']['main']['App']['ListAudit'](arg1);
}

export function ListClients(arg1) {
  return window['go']['main']['App']['ListClients'](arg1);
}

export function ListDriversAvailable(arg1) {
  return window['go']['main']['App']['ListDriversAvailable'](arg1);
}

export function ListOrders(arg1) {
  return window['go']['main']['App']['ListOrders'](arg1);
}

export function ListTariffs(arg1) {
  return window['go']['main']['App']['ListTariffs'](arg1);
}

export function ListUsers(arg1) {
  return window['go']['main']['App']['ListUsers'](arg1);
}

export function ListVehicles(arg1) {
  return window['go']['main']['App']['ListVehicles'](arg1);
}

export function ListWaybills(arg1) {
  return window['go']['main']['App']['ListWaybills'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function LoginWithCredentials(arg1, arg2) {
  return window['go']['main']['App']['LoginWithCredentials'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function Me(arg1) {
  return window['go']['main']['App']['Me'](arg1);
}

export function OpenShift(arg1, arg2) {
  return window['go']['main']['App']['OpenShift'](arg1, arg2);
}

export function PreviewPrice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PreviewPrice'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveClient(arg1, arg2) {
  return window['go']['main']['App']['SaveClient'](arg1, arg2);
}

export function SaveTariff(arg1, arg2) {
  return window['go']['main']['App']['SaveTariff'](arg1, arg2);
}

export function SaveVehicle(arg1, arg2) {
  return window['go']['main']['App']['SaveVehicle'](arg1, arg2);
}

export function ShiftStatus(arg1) {
  return window['go']['main']['App']['ShiftStatus'](arg1);
}

export function UpdateOrderStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateOrderStatus'](arg1, arg2, arg3);
}

export function VehicleSchedule(arg1) {
  return window['go']['main']['App']['VehicleSchedule'](arg1);
}
