// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CloseShift(arg1:string,arg2:models.CloseShiftRequest):Promise<models.CloseShiftResult>;

export function CreateOrder(arg1:string,arg2:models.CreateOrderRequest):Promise<models.Order>;

export function CreateUser(arg1:string,arg2:models.User,arg3:string):Promise<models.User>;

export function Dashboard(arg1:string):Promise<models.DashboardStats>;

export function DriverRating(arg1:string):Promise<Array<Record<string, any>>>;

export function GetDataDir():Promise<string>;

export function ListAudit(arg1:string):Promise<Array<models.AuditEntry>>;

export function ListClients(arg1:string):Promise<Array<models.Client>>;

export function ListOrders(arg1:string):Promise<Array<models.Order>>;

export function ListTariffs(arg1:string):Promise<Array<models.Tariff>>;

export function ListUsers(arg1:string):Promise<Array<models.User>>;

export function ListVehicles(arg1:string):Promise<Array<models.Vehicle>>;

export function ListWaybills(arg1:string):Promise<Array<models.Waybill>>;

export function Login(arg1:models.LoginRequest):Promise<models.LoginResponse>;

export function Logout(arg1:string):Promise<void>;

export function Me(arg1:string):Promise<models.User>;

export function PreviewPrice(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<number>;

export function SaveClient(arg1:string,arg2:models.Client):Promise<models.Client>;

export function SaveTariff(arg1:string,arg2:models.Tariff):Promise<models.Tariff>;

export function SaveVehicle(arg1:string,arg2:models.Vehicle):Promise<models.Vehicle>;

export function UpdateOrderStatus(arg1:string,arg2:string,arg3:string):Promise<models.Order>;

export function VehicleSchedule(arg1:string):Promise<Array<models.VehicleScheduleItem>>;
